{% set version = "8.0.4" %}

package:
  name: ipywidgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/i/ipywidgets/ipywidgets-{{ version }}.tar.gz
  sha256: c0005a77a47d77889cafed892b58e33b4a2a96712154404c6548ec22272811ea

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - ipykernel >=4.5.1
    - ipython >=6.1.0
    - jupyterlab_widgets >=3.0.4,<4.0.0
    - nbformat >=4.2.0
    - python >=3.7
    - traitlets >=4.3.1
    - widgetsnbextension >=4.0.4,<5.0.0
test:
  requires:
    - jsonschema
    - pip
    - pytest-cov
    - pytz
  imports:
    - ipywidgets
  commands:
    - pip check
    - pytest -vv --pyargs ipywidgets --cov=ipywidgets --cov-report=term-missing:skip-covered --no-cov-on-fail

about:
  home: https://github.com/ipython/ipywidgets
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Jupyter Interactive Widgets
  description: |
    ipywidgets are interactive HTML widgets for Jupyter notebooks and the IPython kernel.
  doc_url: https://ipywidgets.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jupyter-widgets/ipywidgets/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - SylvainCorlay
    - willingc
    - jasongrout
    - maartenbreddels
    - pbugnion
    - jtpio
    - martinRenou
    - vidartf
    - bollwyvl
